FROM --platform=linux/amd64 ruby:3.4.11-alpine@sha256:50133d02799e7da49a1e0bd16d865701622fd61d150a8cd3463edf0016504af5

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN set -ex && \
  adduser -h $HOME -s /bin/false -D -S -G root ruby && \
  chmod g+w $HOME && \
  apk add --update --no-cache make gcc libc-dev git

RUN gem install bundler -v "~> 2.5"
COPY Gemfile Gemfile.lock $HOME/
RUN bundle install --no-cache
