FROM --platform=linux/amd64 ruby:3.4.11-slim@sha256:976f45719573889b0ef02fcff5fd7a486cb09a56ad11c472d51d49604c31d6ab

RUN apt-get update && apt-get install -y \
    curl \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV HOME=/app
WORKDIR $HOME

RUN useradd --create-home --home-dir $HOME user \
    && mkdir -p $HOME \
    && chown -R user:user $HOME

RUN gem install bundler:2.5.18
RUN bundle install
COPY Rakefile README.md Gemfile Gemfile.lock VERSION $HOME/
COPY tasks $HOME/tasks
COPY packaging $HOME/packaging
RUN bundle exec rake package