FROM --platform=linux/amd64 ruby:3.4.11-slim@sha256:c12225b6a73743f943530d9e610f4ae78e0dbcffdcf797b01522a55f7d25acb3

RUN apt-get update && apt-get install -y \
    curl \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV HOME=/app
WORKDIR $HOME

RUN useradd --create-home --home-dir $HOME user \
    && mkdir -p $HOME \
    && chown -R user:user $HOME

RUN gem install bundler:2.5.18
RUN bundle install
COPY Rakefile README.md Gemfile Gemfile.lock VERSION $HOME/
COPY tasks $HOME/tasks
COPY packaging $HOME/packaging
RUN bundle exec rake package