source 'https://rubygems.org'

gem "pact", "1.67.3"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.12.4"
gem "pact-provider-verifier", "1.39.1"
gem "pact_broker-client", "1.77.0"
gem "webrick", "1.9.2"
# locked to native extensions supported by traveling-ruby
# https://github.com/trubygems/traveling-ruby/releases/tag/rel-20251122
gem "json", "2.16.0"
gem "bigdecimal", "3.3.1"
gem "fiddle", "1.1.8"
gem "io-console", "0.8.1"